### ISSUE TITLE
Atomic groups not supported

### ISSUE THREAD

**Issue by danpaul88** [javallone/regexper-static#13]
The ?> syntax for an atomic matching group is not recognised as valid syntax by Regexper,giving the following error (using a simplified example);

Error: Line 1: expected "?"
^(?>[a-z]+;)*$
   ^

Replacing the atomic matching group with a non-capturing group;

^(?:[a-z]+;)*$

produces the expected output. I'd expected the output for an atomic group ( ?> ) to match that for a non-capturing group ( ?: )

**Comment by javallone** [comment]
Atomic groups are not supported by JavaScript's regular expression syntax (which is the only syntax that Regexper currently supports). I do plan on eventually adding support for other regular expression flavors, and will track that work with issue #4.
