### ISSUE TITLE
Screen is short for a large expresion

### ISSUE THREAD

**Issue by angelbladex** [javallone/regexper-static#18]
Testing with this expression 

/^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i

, Screen is short for draw a good diagram on http://regexper.com/

**Comment by javallone** [comment]
It should be possible to scroll the image if it is large than your browser window. Which browser are you using (it is possible that the styling isn't being applied correctly)?

**Comment by angelbladex** [comment]
Ok Ok. I tried on other browsers and can to scroll the image. Thanks.
