### ISSUE TITLE
Positive / Negative Lookbehind Support

### ISSUE THREAD

**Issue by Nessworthy** [javallone/regexper-static#2]
As awesome as this bit of kit is, it appears that the tool does not support [lookbehinds](http://www.regular-expressions.info/lookaround.html#lookbehind) (positive or negative).

Example: `(?<=H)ello`
Returns: 

    Error: Line 1: expected "?"
    (?<=H)ello
     ^

Is this intended?

**Comment by javallone** [comment]
It is (currently) intended. Right now, it only supports Javascript's flavor of regular expressions, which don't include lookbehinds.

I'm planning on adding support for other flavors at some point, but just haven't had the chance.

**Comment by javallone** [comment]
I've added issue #4 to track the work to add support for other regex flavors. Closing this issue.
