### ISSUE TITLE
Doesn't accept ^[a-zA-Z_][^\\\/\:\*\?\""\<\>\|\`\'\^%\#]*(?<![\.\s])$ while it is a valid REGEX

### ISSUE THREAD

**Issue by arefkn** [javallone/regexper-static#20]
^[a-zA-Z_][^\\\/\:\*\?\""\<\>\|\`\'\^%\#]*(?<![\.\s])$
doesn't work. but it's valid on https://regex101.com/

I guess because the end part is the "look behind" regex which isn't supported by javascript.

**Comment by javallone** [comment]
Regexper currently only supports JavaScript-style regular expression syntax, which does not include lookbehind (`?<!` or `?<=` at the beginning of a set of parenthesis).
