### ISSUE TITLE
slightly confusing visual of the "repeat" regex function

### ISSUE THREAD

**Issue by pokeball99** [javallone/regexper-static#27]
(([b-df-hj-np-tv-xz][aeiou]){5})|(([B-DF-HJ-NP-TV-XZ][AEIOU]){5})
says repeat 4 times, while i understand why it is shown that way, it does make it slightly confusing

**Comment by ThibWeb** [comment]
Hey @pokeball99, I think this is the same issue as https://github.com/javallone/regexper-static/issues/14.

**Comment by javallone** [comment]
Closing as duplicate of #14
