### ISSUE TITLE
Same expression, different result.

### ISSUE THREAD

**Issue by suyuTech** [javallone/regexper-static#31]
I tested same expression but got different result.
![image](https://cloud.githubusercontent.com/assets/13642123/19422927/b60ba07e-944d-11e6-8e9b-7237df86beff.png)

vs.

![image](https://cloud.githubusercontent.com/assets/13642123/19422932/be7c689c-944d-11e6-866c-cc0488ecc949.png)

**Comment by thibaudcolas** [comment]
See #14 – this is the intended behavior.

**Comment by suyuTech** [comment]
@thibaudcolas Thank you very much!I should have checked the issues list first.
