### ISSUE TITLE
Let's get sticky

### ISSUE THREAD

**Issue by javatlacati** [javallone/regexper-static#33]
Can you add support for the y modifier?

**Comment by javatlacati** [comment]
So this is a won't fix???

**Comment by javallone** [comment]
No, it's fixed at up on the site right now. Change 988f5ca added support for `/some expression/y` for sticky and `/some expression/u` for unicode support.

Sorry for the confusion, I'll try to add better notes in the future. To be honest, I was confused about why I closed this for a moment.
