### ISSUE TITLE
Pattern repeat count off by one error

### ISSUE THREAD

**Issue by nikcorg** [javallone/regexper-static#44]
Hello,

Whilst using your excellent tool, I noticed repetition count has an off by one error. See attached screen shot or visit the [demo](https://regexper.com/#%2F%5Eprefix_%5B%5Cda-z%5D%7B8%7D-(%3F%3A%5B%5Cda-z%5D%7B4%7D-)%7B3%7D%5B%5Cda-z%5D%7B12%7D%24%2F).

![regexper](https://user-images.githubusercontent.com/816988/33493538-499f8c62-d6b8-11e7-8831-4cb3b029c8a4.png)

At the same time, I tested other variants of repetition for completeness.

- `{,8}` is treated as a literal value instead of `at most 8 times`, i.e. seemingly doesn't parse
- `{8,}` correctly (save for the off-by-one) becomes `7+`
- `{0,8}` correctly (save for the off-by-one) becomes `at most 7 times`
- `{1,8}` incorrectly becomes `at most 7 times`, instead of `1...8 times`
- `{2,8}` correctly (save for the off-by-one) becomes `1...7 times`

**Comment by CubicPill** [comment]
Not an error, I think. It means the pattern appears once and then repeat x-1 times, that's {x}. A bit confusing though...

**Comment by nikcorg** [comment]
@CubicPill oh, I can see that now, I think you're right. Quite confusing indeed.

**Comment by nikcorg** [comment]
Closing as is ostensibly not a bug, but merely a misunderstanding of the UI.
