### ISSUE TITLE
Off by one for "at most" calculation

### ISSUE THREAD

**Issue by phillipb** [javallone/regexper-static#45]
https://regexper.com/#%5EM%7B0%2C4%7D(CM%7CCD%7CD%3FC%7B0%2C3%7D)(XC%7CXL%7CL%3FX%7B0%2C3%7D)(IX%7CIV%7CV%3FI%7B0%2C3%7D)%24%0A

**Comment by javallone** [comment]
This is a duplicate, and an issue that is brought up occasionally. See #14 for a more in-depth discussion. I'm open to improvements to improve the clarity of these loop descriptions since they do seem to trip up people every now and then.
