### ISSUE TITLE
Support for many file types and reuse of hash

### ISSUE THREAD

**Issue by Schizo** [javallone/regexper-static#46]
I love this project and would like to put here two suggestions

1) Next to SVG, **preview** as **PNG**:
Not every visualizer is guaranteed to visualize the same SVG, let's say you want to download the SVG and visualize it in an APP, that might not be the same result. (pysvg for example interprets the svg differently, missing circles)

2) Reuse of previously created hashes
For valid regex I would suggest to not re-generate the hash URL but store those. Not sure what limitations the current server has, but having one hash for all the same regexes makes sense from the perspective of saying "those hashes are the same.

If the PNG wouldn't be a deal in terms of disk space on your server, I could help out with that.

**Comment by javallone** [comment]
I've added PNG download support.

As for the hash URLs, I assume you're talking about the URLs for the download links. Those are actually URLs generated in the browser that point to an Javascript blob object in memory on the client side. There actually isn't any server-side code. 😄
