### ISSUE TITLE
Regexp group number show wrong

### ISSUE THREAD

**Issue by Nuintun** [javallone/regexper-static#7]
Here is a regexp:
```js
(@import\s+url\s*\(.+?\);?|@import\s+(['"]).+?\2;?)
```
the right group number will be:
![right](https://cloud.githubusercontent.com/assets/1730277/6631688/438d7f90-c965-11e4-95c7-39630ea6af34.png)

but in regexper:
![wrong](https://cloud.githubusercontent.com/assets/1730277/6631693/505fbcc4-c965-11e4-97c0-2588583ca759.png)

**Comment by javallone** [comment]
This bug actually went back to some rework I did before the site was even launched (it was caused by e362a545513848612fb64b36fa0bb64917bae3c9 for the curious). I'm amazed it has been around this long. 

Thank you very much for catching and reporting it!
